//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_greatassault_b3
//
// Download @: http://dwl.17buddies.net/link/map/17042/cs_greatassault_b3.html
//
//////////////////////////////////////////////////////////
gfx/env/city_dayup.tga
gfx/env/city_daydn.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayft.tga
gfx/env/city_daybk.tga

models/cs_greatassault/cs_ga_airconditioner.mdl
models/cs_greatassault/cs_ga_ampoule.mdl
models/cs_greatassault/cs_ga_brush.mdl
models/cs_greatassault/cs_ga_bulb.mdl
models/cs_greatassault/cs_ga_bush1.mdl
models/cs_greatassault/cs_ga_bush2.mdl
models/cs_greatassault/cs_ga_bush3.mdl
models/cs_greatassault/cs_ga_camera.mdl
models/cs_greatassault/cs_ga_cardboard.mdl
models/cs_greatassault/cs_ga_couch.mdl
models/cs_greatassault/cs_ga_deskchair.mdl
models/cs_greatassault/cs_ga_dolly.mdl
models/cs_greatassault/cs_ga_femhostage1.mdl
models/cs_greatassault/cs_ga_femhostage2.mdl
models/cs_greatassault/cs_ga_filecabinet.mdl
models/cs_greatassault/cs_ga_flatscreen.mdl
models/cs_greatassault/cs_ga_lidopen.mdl
models/cs_greatassault/cs_ga_machinery.mdl
models/cs_greatassault/cs_ga_oiltank.mdl
models/cs_greatassault/cs_ga_palette.mdl
models/cs_greatassault/cs_ga_powerpole.mdl
models/cs_greatassault/cs_ga_put.mdl
models/cs_greatassault/cs_ga_putclosed.mdl
models/cs_greatassault/cs_ga_qtruck.mdl
models/cs_greatassault/cs_ga_shelves.mdl
models/cs_greatassault/cs_ga_shelves2.mdl
models/cs_greatassault/cs_ga_stairdouble.mdl
models/cs_greatassault/cs_ga_stairsingle.mdl
models/cs_greatassault/cs_ga_telephone.mdl
models/cs_greatassault/cs_ga_trash1.mdl
models/cs_greatassault/cs_ga_trash2.mdl
models/cs_greatassault/cs_ga_trashcan.mdl
models/cs_greatassault/cs_ga_tree1.mdl
models/cs_greatassault/cs_ga_tree2.mdl
models/cs_greatassault/cs_ga_truck.mdl
models/cs_greatassault/cs_ga_watertower.mdl
models/cs_greatassault/cs_ga_wlight.mdl
models/hostage.mdl
 
sound/cs_greatassault/ambience6.wav
sound/cs_greatassault/computalk2.wav
sound/cs_greatassault/door_elec_gatestop.wav
sound/cs_greatassault/door_wood_locked1.wav
sound/cs_greatassault/electric_hum2.wav
sound/cs_greatassault/elev_shaft1.wav
sound/cs_greatassault/engine4.wav
sound/cs_greatassault/fan3.wav
sound/cs_greatassault/music_elevator.wav
sound/cs_greatassault/plaza_amb.wav
sound/cs_greatassault/security_alarm.wav
sound/cs_greatassault/town_ambience.wav
sound/cs_greatassault/water_rivulet_loop2.wav
sound/cs_greatassault/waterleak_loop1.wav
 
sprites/cs_greatassault/glow01.spr 

overviews/cs_greatassault_b3.bmp
overviews/cs_greatassault_b3.txt
