gfx/detail/dt_fabric2.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/env/junglebk.tga
gfx/env/jungledn.tga
gfx/env/jungleft.tga
gfx/env/junglelf.tga
gfx/env/junglert.tga
gfx/env/jungleup.tga
maps/de_aztec_cz.res
maps/de_aztec_cz.txt
maps/de_aztec_cz_detail.txt
models/props/bush_fern_small.mdl
models/props/skeleton.mdl
overviews/de_aztec_cz.bmp
overviews/de_aztec_cz.txt
czde_aztec.wad
czritual_standard.wad
