maps/de_ciel_b1.res
maps/de_ciel_b1.txt
maps/de_ciel_b1_detail.txt
readme_de_ciel_b1.txt
cs_assault.wad
cs_office.wad
cs_office_packed.wad
de_vegas_cz_packed.wad
halflife.wad
gfx/detail/dt_carpet1.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
models/props/fan_ceiling.mdl
overviews/de_ciel_b1.bmp
overviews/de_ciel_b1.txt
sound/ambience/lv_neon.wav
sprite/yelflare1.spr
maps/de_ciel_b1.bsp